// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASj-eezymuI7YLfMy-K_G8NNPgRwfiEyY',
    appId: '1:902369996875:web:dd415da3c1b23fb9cf1dce',
    messagingSenderId: '902369996875',
    projectId: 'whatsapp-clone-f93e7',
    authDomain: 'whatsapp-clone-f93e7.firebaseapp.com',
    storageBucket: 'whatsapp-clone-f93e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgB4olfSQH3bjcsGsRyLCldxEk3dt1g0',
    appId: '1:902369996875:android:d118eba4acd4724fcf1dce',
    messagingSenderId: '902369996875',
    projectId: 'whatsapp-clone-f93e7',
    storageBucket: 'whatsapp-clone-f93e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGA7cMzusKkI7m0hmfQkOO8sucF__64o0',
    appId: '1:902369996875:ios:37a1c7c536829546cf1dce',
    messagingSenderId: '902369996875',
    projectId: 'whatsapp-clone-f93e7',
    storageBucket: 'whatsapp-clone-f93e7.appspot.com',
    iosClientId: '902369996875-lq4p81ipqgpcb921nb7vrigfno7sqfqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGA7cMzusKkI7m0hmfQkOO8sucF__64o0',
    appId: '1:902369996875:ios:37a1c7c536829546cf1dce',
    messagingSenderId: '902369996875',
    projectId: 'whatsapp-clone-f93e7',
    storageBucket: 'whatsapp-clone-f93e7.appspot.com',
    iosClientId: '902369996875-lq4p81ipqgpcb921nb7vrigfno7sqfqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
